version: '3.8'

services:
  web:
    container_name: web-server
    volumes:
      - ./ShippHi:/var/www/html
      - ./ShippHi/uploads:/var/www/html/uploads
    ports:
      - "8080:80"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: shipphi
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root1234
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
